### ISSUE TITLE
App is not getting deployed.

### ISSUE THREAD

**Issue by allpratik** [Q42/meteor-gce#8]
I followed the each step carefully given in the readme. Only one more additional change was from ```--zone "europe-west1-a"```  to ```--zone "europe-west1-b"```. This particular location was changed because Google deprecated europe-west1-a . 
I do get my external ip but nothing is accessible over there. Can someone please help me out of it?
Moreover, had anyone tried to use mup for deployment on gce?
Thanks in advance for help!

**Comment by chees** [comment]
You might have to manually open the firewall in GCE for port 80 if that wasn't done yet for your project. Could you check if that works?
If not, you can look at the boot log of your GCE instance (go to your instance in the cloud console website and then click View Output all the way at the bottom). Does it show there that any of the steps failed?

I did check out MUP, but even though it claims it works on Debian it doesn't. Back when I tried it there was no official Ubuntu image for GCE yet, but since now there is you could try that. It will probably work.

**Comment by allpratik** [comment]
Update: Issue got resolved when Interoperability under storage access was permitted to the project. Everything is working Fine as of now. Please just make change of above ```--zone "europe-west1-a"``` to ```--zone "europe-west1-b"``` . 
Thanks n cheers!!

**Comment by allpratik** [comment]
@chees The above app was showing "502 Bad Gateway" error after some time and continued to show it until I killed the instance. 
Followed again everything for fresh deployment, now even this new deployment is also showing the same error.

I tried searching for errors in console log, but everything was fine. Though there were some messages related mongodb filesystem creation as ```"VFS: Can't Find ext4 filesystem"``` 

Firewall rules are also okay and and port 80 is also open.
Where am I going wrong?

Thanks in advance for your help!

**Comment by chees** [comment]
Was the disk properly added to your instance?

**Comment by allpratik** [comment]
Yeah, everything was in place. I just deployed another app, and it worked after an hour. I don't know why sometimes it works and sometimes it just simply fail? Anyways, Thanks for your reply!

**Comment by chees** [comment]
Hmm, doesn't sound good that it's randomly failing. Would love to know if
you find out some more about when it fails for you.

On Thu, Mar 26, 2015 at 3:43 PM, Pratik Khandagale <notifications@github.com

**Comment by allpratik** [comment]
Sure, Some more deployments are on the way. I will try out to spot some specific pattern.
